package com.surrealdev.temporal.client

import com.surrealdev.temporal.annotation.InternalTemporalApi
import com.surrealdev.temporal.common.TemporalPayload
import com.surrealdev.temporal.common.TemporalPayloads
import com.surrealdev.temporal.serialization.PayloadSerializer
import java.util.UUID
import kotlin.reflect.KClass
import kotlin.reflect.KType
import kotlin.reflect.full.starProjectedType
import kotlin.time.Duration

/**
 * A [WorkflowHandle] that knows the workflow's typed return type at construction time.
 *
 * The compiler plugin synthesises a `start(...)` function on each `@Workflow` class's companion
 * object that returns a (subtype of) `TypedWorkflowHandle<R>`, where `R` is read from the user's
 * `@WorkflowRun` method's return type. Callers can then write
 *
 * ```
 * val handle = MyWorkflow.start(client, "queue", arg)
 * val result: String = handle.result()   // no <R> at the call site
 * ```
 *
 * The result-type discriminator is captured as a [KType] (instead of a reified type parameter
 * on the class) because Kotlin classes cannot have reified parameters; the IR-time body filler
 * captures `typeOf<R>()` at synthesis time and stores it in the [resultType] field.
 *
 * Subclasses synthesized per workflow expose typed signal/query/update methods that delegate to
 * the underlying [WorkflowHandle].
 */
open class TypedWorkflowHandle<out R>
    @InternalTemporalApi
    constructor(
        val handle: WorkflowHandle,
        @PublishedApi internal val resultType: KType,
    ) {
        val workflowId: String get() = handle.workflowId
        val runId: String? get() = handle.runId

        @Suppress("UNCHECKED_CAST")
        suspend fun result(timeout: Duration = Duration.INFINITE): R {
            val payload: TemporalPayload? = handle.resultPayload(timeout)
            return deserializeWithKType(payload, resultType, handle.serializer) as R
        }
    }

/**
 * Non-reified deserialize for [TypedWorkflowHandle]. Mirrors the semantics of the existing
 * `inline reified` `deserializePayload` extension in `HandleResultExtensions.kt` but takes a
 * pre-computed [KType] instead of inferring from a reified `R`.
 */
@PublishedApi
internal fun deserializeWithKType(
    payload: TemporalPayload?,
    returnType: KType,
    serializer: PayloadSerializer,
): Any? {
    if (returnType.classifier == Unit::class) {
        return Unit
    }
    return if (payload == null || (payload.encoding == null && payload.data.isEmpty())) {
        null
    } else {
        serializer.deserialize(returnType, payload)
    }
}

/**
 * Companion convenience: server-side workflow IDs are generated by [java.util.UUID.randomUUID]
 * when the user doesn't pass one. The plugin always emits a fresh UUID at the start callsite
 * via this helper rather than threading a default value through annotation arguments.
 */
@PublishedApi
internal fun newWorkflowId(): String = UUID.randomUUID().toString()

/**
 * Compiler-plugin helper for materialising a [KType] from a [KClass] reference. The IR body
 * filler emits `typeFromClass(<argClass>::class)` rather than constructing `typeOf<T>()`
 * intrinsics — class references are trivial to build at IR time, while `typeOf` desugars to a
 * compiler-internal call sequence that's easier to delegate via this helper.
 *
 * **Limitation:** for generic types (e.g. `List<String>`) this only captures the raw class —
 * inner type arguments are lost. Workflows using generic arg/return types should use simple
 * non-generic wrapper data classes for now. A follow-up may emit a real `typeOf` intrinsic.
 */
@PublishedApi
internal fun typeFromClass(cls: KClass<*>): KType = cls.starProjectedType

/**
 * Compiler-plugin helper: starts a workflow and returns the raw [WorkflowHandle]. The plugin
 * wraps the return value in a per-workflow `<UserClass>.Handle` (which extends
 * [TypedWorkflowHandle]) at the call site.
 *
 * `null` [argType] means the user's `@WorkflowRun` method takes no value parameters; the
 * workflow is started with empty payloads.
 */
@PublishedApi
@OptIn(InternalTemporalApi::class)
internal suspend fun startWorkflowGetHandle(
    client: TemporalClient,
    workflowType: String,
    taskQueue: String,
    workflowId: String,
    arg: Any?,
    argType: KType?,
    options: WorkflowStartOptions,
): WorkflowHandle {
    val payloads =
        if (argType == null) {
            TemporalPayloads.EMPTY
        } else {
            val payload = client.serializer.serialize(argType, arg)
            TemporalPayloads.of(listOf(payload))
        }
    return client.startWorkflowWithPayloads(
        workflowType = workflowType,
        taskQueue = taskQueue,
        workflowId = workflowId,
        args = payloads,
        options = options,
    )
}

/**
 * Non-reified, single-arg activity dispatch used by the compiler plugin to fill
 * `activity("name") { ... }` call sites that have been lifted by Stage 8.6 inline-activity
 * lowering. The lifted lambda body lives in a top-level `@Activity` function registered on the
 * same task queue; this helper is what the rewritten call site invokes from inside the workflow
 * body.
 *
 * `null` [argType] means the inline activity took no value parameters; dispatched with empty
 * payloads.
 *
 * @param startToCloseMs default 1 minute. Inline activities have no syntactic place to set
 * options yet; this default keeps things working for development. Future stages can add
 * `activity(name, options=...) { ... }` overloads.
 */
@PublishedApi
@OptIn(InternalTemporalApi::class)
internal suspend fun startActivityTyped(
    workflowContext: com.surrealdev.temporal.workflow.WorkflowContext,
    activityType: String,
    arg: Any?,
    argType: KType?,
    resultType: KType,
    startToCloseMs: Long = 60_000,
): Any? {
    val payloads =
        if (argType == null) {
            TemporalPayloads.EMPTY
        } else {
            val payload = workflowContext.serializer.serialize(argType, arg)
            TemporalPayloads.of(listOf(payload))
        }
    val options =
        com.surrealdev.temporal.workflow.ActivityOptions(
            startToCloseTimeout = Duration.run { startToCloseMs.milliseconds },
        )
    val handle =
        workflowContext.startActivityWithPayloads(
            activityType = activityType,
            args = payloads,
            options = options,
        )
    val resultPayload = handle.resultPayload()
    return deserializeWithKType(resultPayload, resultType, workflowContext.serializer)
}
