package com.surrealdev.temporal.client

import com.surrealdev.temporal.annotation.InternalTemporalApi
import com.surrealdev.temporal.common.TemporalPayload
import com.surrealdev.temporal.common.TemporalPayloads
import com.surrealdev.temporal.serialization.PayloadSerializer
import java.util.UUID
import kotlin.reflect.KClass
import kotlin.reflect.KType
import kotlin.reflect.full.starProjectedType
import kotlin.time.Duration

/**
 * A [WorkflowHandle] that knows the workflow's typed return type at construction time.
 *
 * The compiler plugin synthesises a `start(...)` function on each `@Workflow` class's companion
 * object that returns a (subtype of) `TypedWorkflowHandle<R>`, where `R` is read from the user's
 * `@WorkflowRun` method's return type. Callers can then write
 *
 * ```
 * val handle = MyWorkflow.start(client, "queue", arg)
 * val result: String = handle.result()   // no <R> at the call site
 * ```
 *
 * The result-type discriminator is captured as a [KType] (instead of a reified type parameter
 * on the class) because Kotlin classes cannot have reified parameters; the IR-time body filler
 * captures `typeOf<R>()` at synthesis time and stores it in the [resultType] field.
 *
 * Subclasses synthesized per workflow expose typed signal/query/update methods that delegate to
 * the underlying [WorkflowHandle].
 */
open class TypedWorkflowHandle<out R>
    @InternalTemporalApi
    constructor(
        val handle: WorkflowHandle,
        @PublishedApi internal val resultType: KType,
    ) {
        val workflowId: String get() = handle.workflowId
        val runId: String? get() = handle.runId

        @Suppress("UNCHECKED_CAST")
        suspend fun result(timeout: Duration = Duration.INFINITE): R {
            val payload: TemporalPayload? = handle.resultPayload(timeout)
            return deserializeWithKType(payload, resultType, handle.serializer) as R
        }
    }

/**
 * Non-reified deserialize for [TypedWorkflowHandle]. Mirrors the semantics of the existing
 * `inline reified` `deserializePayload` extension in `HandleResultExtensions.kt` but takes a
 * pre-computed [KType] instead of inferring from a reified `R`.
 */
@PublishedApi
internal fun deserializeWithKType(
    payload: TemporalPayload?,
    returnType: KType,
    serializer: PayloadSerializer,
): Any? {
    if (returnType.classifier == Unit::class) {
        return Unit
    }
    return if (payload == null || (payload.encoding == null && payload.data.isEmpty())) {
        null
    } else {
        serializer.deserialize(returnType, payload)
    }
}

/**
 * Companion convenience: server-side workflow IDs are generated by [java.util.UUID.randomUUID]
 * when the user doesn't pass one. The plugin always emits a fresh UUID at the start callsite
 * via this helper rather than threading a default value through annotation arguments.
 */
@PublishedApi
internal fun newWorkflowId(): String = UUID.randomUUID().toString()

/**
 * Compiler-plugin helper for materialising a [KType] from a [KClass] reference. The IR body
 * filler emits `typeFromClass(<argClass>::class)` rather than constructing `typeOf<T>()`
 * intrinsics — class references are trivial to build at IR time, while `typeOf` desugars to a
 * compiler-internal call sequence that's easier to delegate via this helper.
 *
 * **Limitation:** for generic types (e.g. `List<String>`) this only captures the raw class —
 * inner type arguments are lost. Workflows using generic arg/return types should use simple
 * non-generic wrapper data classes for now. A follow-up may emit a real `typeOf` intrinsic.
 */
@PublishedApi
internal fun typeFromClass(cls: KClass<*>): KType = cls.starProjectedType

/**
 * Compiler-plugin helper: starts a workflow and returns the raw [WorkflowHandle]. The plugin
 * wraps the return value in a per-workflow `<UserClass>.Handle` (which extends
 * [TypedWorkflowHandle]) at the call site.
 *
 * `null` [argType] means the user's `@WorkflowRun` method takes no value parameters; the
 * workflow is started with empty payloads.
 */
@PublishedApi
@OptIn(InternalTemporalApi::class)
internal suspend fun startWorkflowGetHandle(
    client: TemporalClient,
    workflowType: String,
    taskQueue: String,
    workflowId: String,
    arg: Any?,
    argType: KType?,
    options: WorkflowStartOptions,
): WorkflowHandle {
    val payloads =
        if (argType == null) {
            TemporalPayloads.EMPTY
        } else {
            val payload = client.serializer.serialize(argType, arg)
            TemporalPayloads.of(listOf(payload))
        }
    return client.startWorkflowWithPayloads(
        workflowType = workflowType,
        taskQueue = taskQueue,
        workflowId = workflowId,
        args = payloads,
        options = options,
    )
}

/**
 * Compiler-plugin helper used to fill the rewritten `activity("name") { ... }` call sites
 * inside `@WorkflowRun` methods after Stage 8.6 inline-activity lowering. The lifted lambda
 * body lives in a top-level `@Activity` function registered on the same task queue.
 *
 * `argTypesAndValues` is laid out as `[KType_1, value_1, KType_2, value_2, ...]` (alternating
 * pairs) and may be empty for no-arg activities. Captures inside the inline lambda are passed
 * as activity args via this same vararg, one pair per captured value.
 *
 * @param startToCloseMs default 1 minute. Inline activities have no syntactic place to set
 * options yet; this default keeps things working for development.
 */
@PublishedApi
@OptIn(InternalTemporalApi::class)
internal suspend fun startActivityTyped(
    workflowContext: com.surrealdev.temporal.workflow.WorkflowContext,
    activityType: String,
    resultType: KType,
    startToCloseMs: Long,
    argTypesAndValues: Array<out Any?>,
): Any? {
    val payloads = serializeArgs(workflowContext.serializer, argTypesAndValues)
    val options =
        com.surrealdev.temporal.workflow.ActivityOptions(
            startToCloseTimeout = Duration.run { startToCloseMs.milliseconds },
        )
    val handle =
        workflowContext.startActivityWithPayloads(
            activityType = activityType,
            args = payloads,
            options = options,
        )
    val resultPayload = handle.resultPayload()
    return deserializeWithKType(resultPayload, resultType, workflowContext.serializer)
}

/**
 * Local-activity counterpart of [startActivityTyped] — fills the `inlineLocalActivity(...)`
 * call sites. Local activities run in the workflow worker process (no separate task queue
 * dispatch), suitable for short deterministic side effects.
 */
@PublishedApi
@OptIn(InternalTemporalApi::class)
internal suspend fun startLocalActivityTyped(
    workflowContext: com.surrealdev.temporal.workflow.WorkflowContext,
    activityType: String,
    resultType: KType,
    startToCloseMs: Long,
    argTypesAndValues: Array<out Any?>,
): Any? {
    val payloads = serializeArgs(workflowContext.serializer, argTypesAndValues)
    val options =
        com.surrealdev.temporal.workflow.LocalActivityOptions(
            startToCloseTimeout = Duration.run { startToCloseMs.milliseconds },
        )
    val handle =
        workflowContext.startLocalActivityWithPayloads(
            activityType = activityType,
            args = payloads,
            options = options,
        )
    val resultPayload = handle.resultPayload()
    return deserializeWithKType(resultPayload, resultType, workflowContext.serializer)
}

/**
 * Compiler-plugin helpers for typed `@Signal` / `@Query` / `@Update` wrappers on
 * `<UserClass>.Handle<R>`. Each takes a `vararg` of pairs `(KType, Any?)` so the IR pass
 * can build call sites without constructing two parallel lists.
 *
 * Convention: `argTypesAndValues` is laid out as `[KType, Any?, KType, Any?, ...]` in even/odd
 * positions. Empty vararg → no payloads. The plugin emits arrays directly via `IrVararg`.
 */
@PublishedApi
@OptIn(InternalTemporalApi::class)
internal suspend fun signalTyped(
    handle: WorkflowHandle,
    signalName: String,
    argTypesAndValues: Array<out Any?>,
) {
    val payloads = serializeArgs(handle.serializer, argTypesAndValues)
    handle.signalWithPayloads(signalName, payloads)
}

@PublishedApi
@OptIn(InternalTemporalApi::class)
internal suspend fun queryTyped(
    handle: WorkflowHandle,
    queryType: String,
    resultType: KType,
    argTypesAndValues: Array<out Any?>,
): Any? {
    val payloads = serializeArgs(handle.serializer, argTypesAndValues)
    val resultPayloads = handle.queryWithPayloads(queryType, payloads)
    return deserializeFirstPayload(resultPayloads, resultType, handle.serializer)
}

@PublishedApi
@OptIn(InternalTemporalApi::class)
internal suspend fun updateTyped(
    handle: WorkflowHandle,
    updateName: String,
    resultType: KType,
    argTypesAndValues: Array<out Any?>,
): Any? {
    val payloads = serializeArgs(handle.serializer, argTypesAndValues)
    val resultPayloads = handle.updateWithPayloads(updateName, payloads)
    return deserializeFirstPayload(resultPayloads, resultType, handle.serializer)
}

private fun serializeArgs(
    serializer: PayloadSerializer,
    argTypesAndValues: Array<out Any?>,
): TemporalPayloads {
    if (argTypesAndValues.isEmpty()) return TemporalPayloads.EMPTY
    require(argTypesAndValues.size % 2 == 0) {
        "argTypesAndValues must have even length (alternating KType, value); got ${argTypesAndValues.size}"
    }
    val payloads =
        buildList(argTypesAndValues.size / 2) {
            var i = 0
            while (i < argTypesAndValues.size) {
                val type = argTypesAndValues[i] as? KType
                    ?: error("Expected KType at index $i, got ${argTypesAndValues[i]?.javaClass?.name}")
                val value = argTypesAndValues[i + 1]
                add(serializer.serialize(type, value))
                i += 2
            }
        }
    return TemporalPayloads.of(payloads)
}

private fun deserializeFirstPayload(
    payloads: TemporalPayloads,
    resultType: KType,
    serializer: PayloadSerializer,
): Any? {
    if (resultType.classifier == Unit::class) return Unit
    val first: TemporalPayload? = payloads.firstOrNull()
    return if (first == null || (first.encoding == null && first.data.isEmpty())) {
        null
    } else {
        serializer.deserialize(resultType, first)
    }
}
