// The code in this file is a convention plugin - a Gradle mechanism for sharing reusable build logic.
// `buildSrc` is a Gradle-recognized directory and every plugin there will be easily available in the rest of the build.
package buildsrc.convention

import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent
import org.jlleitschuh.gradle.ktlint.KtlintExtension

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin in JVM projects.
    kotlin("jvm")
    // ktlint for code formatting
    id("org.jlleitschuh.gradle.ktlint")
    // Dokka for documentation generation
    id("org.jetbrains.dokka")
}

configure<KtlintExtension> {
    // Bumped from 1.5.0 to support Kotlin 2.3 context parameters used by FIR checker overrides.
    version.set("1.8.0")
    filter {
        exclude("**/generated/**")
        exclude("**/generated-sources/**")
        // Auto-generated by GenerateTests.kt; not worth round-tripping through ktlint.
        exclude("**/test-gen/**")
    }
}

kotlin {
    jvmToolchain(25)
}

// -Pkotlin.lang=<X> retargets every `org.jetbrains.kotlin:*` dependency to that version across
// every module that applies this convention. Mirrors the KGP override in
// `buildSrc/settings.gradle.kts`; together they make `./gradlew … -Pkotlin.lang=2.4.0-Beta2` build
// the entire project at the requested Kotlin. Used by CI matrix legs to validate compatibility
// against upcoming Kotlin releases. compiler-plugin/build.gradle.kts has a narrower
// `-Pkotlin.compiler` override that only affects its compileOnly classpath + CSM template selection.
//
// Skip `-ij` values for the same reason as the buildSrc settings file: those Kotlin builds aren't
// published as kotlin-gradle-plugin / kotlin-stdlib / etc. artifacts. The KEFS forge model
// publishes our compiler-plugin under an `-ij`-prefixed coordinate built against pinned ABI.
providers.gradleProperty("kotlin.lang").orNull
    ?.takeIf { !it.contains("-ij") }
    ?.let { kotlinLangOverride ->
        configurations.configureEach {
            resolutionStrategy.eachDependency {
                if (requested.group == "org.jetbrains.kotlin" && requested.name.startsWith("kotlin-")) {
                    useVersion(kotlinLangOverride)
                    because("kotlin.lang override → $kotlinLangOverride")
                }
            }
        }
    }

// Enable native access for FFM (Foreign Function & Memory) API
val nativeAccessArgs = listOf("--enable-native-access=ALL-UNNAMED")

tasks.withType<Test>().configureEach {
    // Configure all test Gradle tasks to use JUnitPlatform.
    useJUnitPlatform {
        providers.gradleProperty("excludeTags").orNull?.let {
            excludeTags(*it.split(",").toTypedArray())
        }
    }

    // Enable native access for FFM
    jvmArgs(nativeAccessArgs)

    // Log information about all test results, not only the failed ones.
    testLogging {
        events(
            TestLogEvent.FAILED,
            TestLogEvent.PASSED,
            TestLogEvent.SKIPPED,
        )
        exceptionFormat = TestExceptionFormat.FULL
        showStackTraces = true
    }
}

tasks.withType<JavaExec>().configureEach {
    // Enable native access for FFM
    jvmArgs(nativeAccessArgs)
}

// Native library path for internal development
// Skip for core-bridge since it already handles its own native library inclusion
if (project.name != "core-bridge") {
    val nativeLibsDir = rootProject.layout.projectDirectory.dir("core-bridge/build/native-libs")
    val skipNativeBuild = project.findProperty("skipNativeBuild")?.toString()?.toBoolean() ?: false

    // Add native libs to test resources so NativeLoader can find them
    sourceSets {
        test {
            resources.srcDir(nativeLibsDir)
        }
    }

    // Ensure native lib is built before processing test resources
    tasks.named("processTestResources") {
        if (!skipNativeBuild) {
            dependsOn(":core-bridge:copyNativeLib")
        }
    }
}
