

package com.surrealdev.temporal.compiler.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.surrealdev.temporal.compiler.test.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/test/resources/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class TemporalDiagnosticTestGenerated extends AbstractTemporalDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/resources/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("src/test/resources/testData/diagnostics/companion")
  @TestDataPath("$PROJECT_ROOT")
  public class Companion {
    @Test
    public void testAllFilesPresentInCompanion() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/resources/testData/diagnostics/companion"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("ChildHandleSignalWrapper.kt")
    public void testChildHandleSignalWrapper() {
      runTest("src/test/resources/testData/diagnostics/companion/ChildHandleSignalWrapper.kt");
    }

    @Test
    @TestMetadata("ChildHandleSkipsQueryUpdate.kt")
    public void testChildHandleSkipsQueryUpdate() {
      runTest("src/test/resources/testData/diagnostics/companion/ChildHandleSkipsQueryUpdate.kt");
    }

    @Test
    @TestMetadata("ChildWorkflowStartResolves.kt")
    public void testChildWorkflowStartResolves() {
      runTest("src/test/resources/testData/diagnostics/companion/ChildWorkflowStartResolves.kt");
    }

    @Test
    @TestMetadata("ExistingCompanionAugmented.kt")
    public void testExistingCompanionAugmented() {
      runTest("src/test/resources/testData/diagnostics/companion/ExistingCompanionAugmented.kt");
    }

    @Test
    @TestMetadata("ExternalHandleResolves.kt")
    public void testExternalHandleResolves() {
      runTest("src/test/resources/testData/diagnostics/companion/ExternalHandleResolves.kt");
    }

    @Test
    @TestMetadata("ExternalHandleSkipsQueryUpdate.kt")
    public void testExternalHandleSkipsQueryUpdate() {
      runTest("src/test/resources/testData/diagnostics/companion/ExternalHandleSkipsQueryUpdate.kt");
    }

    @Test
    @TestMetadata("HandleQueryWrapper.kt")
    public void testHandleQueryWrapper() {
      runTest("src/test/resources/testData/diagnostics/companion/HandleQueryWrapper.kt");
    }

    @Test
    @TestMetadata("HandleSignalWrapper.kt")
    public void testHandleSignalWrapper() {
      runTest("src/test/resources/testData/diagnostics/companion/HandleSignalWrapper.kt");
    }

    @Test
    @TestMetadata("HandleSkipsDynamicHandlers.kt")
    public void testHandleSkipsDynamicHandlers() {
      runTest("src/test/resources/testData/diagnostics/companion/HandleSkipsDynamicHandlers.kt");
    }

    @Test
    @TestMetadata("HandleSkipsValidators.kt")
    public void testHandleSkipsValidators() {
      runTest("src/test/resources/testData/diagnostics/companion/HandleSkipsValidators.kt");
    }

    @Test
    @TestMetadata("HandleUpdateWrapper.kt")
    public void testHandleUpdateWrapper() {
      runTest("src/test/resources/testData/diagnostics/companion/HandleUpdateWrapper.kt");
    }

    @Test
    @TestMetadata("InlineActivityLifting.kt")
    public void testInlineActivityLifting() {
      runTest("src/test/resources/testData/diagnostics/companion/InlineActivityLifting.kt");
    }

    @Test
    @TestMetadata("InlineActivityWithCaptures.kt")
    public void testInlineActivityWithCaptures() {
      runTest("src/test/resources/testData/diagnostics/companion/InlineActivityWithCaptures.kt");
    }

    @Test
    @TestMetadata("NoArgWorkflowDropsArgParam.kt")
    public void testNoArgWorkflowDropsArgParam() {
      runTest("src/test/resources/testData/diagnostics/companion/NoArgWorkflowDropsArgParam.kt");
    }

    @Test
    @TestMetadata("NoArgWorkflowNoExplicitName.kt")
    public void testNoArgWorkflowNoExplicitName() {
      runTest("src/test/resources/testData/diagnostics/companion/NoArgWorkflowNoExplicitName.kt");
    }
  }

  @Nested
  @TestMetadata("src/test/resources/testData/diagnostics/determinism")
  @TestDataPath("$PROJECT_ROOT")
  public class Determinism {
    @Test
    public void testAllFilesPresentInDeterminism() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/resources/testData/diagnostics/determinism"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("CorrectAsyncUsage.kt")
    public void testCorrectAsyncUsage() {
      runTest("src/test/resources/testData/diagnostics/determinism/CorrectAsyncUsage.kt");
    }

    @Test
    @TestMetadata("DispatchersDefaultUsage.kt")
    public void testDispatchersDefaultUsage() {
      runTest("src/test/resources/testData/diagnostics/determinism/DispatchersDefaultUsage.kt");
    }

    @Test
    @TestMetadata("GlobalScopeFieldUsage.kt")
    public void testGlobalScopeFieldUsage() {
      runTest("src/test/resources/testData/diagnostics/determinism/GlobalScopeFieldUsage.kt");
    }

    @Test
    @TestMetadata("GlobalScopeLaunch.kt")
    public void testGlobalScopeLaunch() {
      runTest("src/test/resources/testData/diagnostics/determinism/GlobalScopeLaunch.kt");
    }

    @Test
    @TestMetadata("GlobalScopeUsage.kt")
    public void testGlobalScopeUsage() {
      runTest("src/test/resources/testData/diagnostics/determinism/GlobalScopeUsage.kt");
    }

    @Test
    @TestMetadata("IndirectDeferredUsage.kt")
    public void testIndirectDeferredUsage() {
      runTest("src/test/resources/testData/diagnostics/determinism/IndirectDeferredUsage.kt");
    }

    @Test
    @TestMetadata("IndirectWithContextUsage.kt")
    public void testIndirectWithContextUsage() {
      runTest("src/test/resources/testData/diagnostics/determinism/IndirectWithContextUsage.kt");
    }

    @Test
    @TestMetadata("NonWorkflowClass.kt")
    public void testNonWorkflowClass() {
      runTest("src/test/resources/testData/diagnostics/determinism/NonWorkflowClass.kt");
    }

    @Test
    @TestMetadata("ValidWorkflow.kt")
    public void testValidWorkflow() {
      runTest("src/test/resources/testData/diagnostics/determinism/ValidWorkflow.kt");
    }

    @Test
    @TestMetadata("WithContextIoUsage.kt")
    public void testWithContextIoUsage() {
      runTest("src/test/resources/testData/diagnostics/determinism/WithContextIoUsage.kt");
    }
  }

  @Nested
  @TestMetadata("src/test/resources/testData/diagnostics/taskqueue")
  @TestDataPath("$PROJECT_ROOT")
  public class Taskqueue {
    @Test
    public void testAllFilesPresentInTaskqueue() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/resources/testData/diagnostics/taskqueue"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("TaskQueueDiagnostic.kt")
    public void testTaskQueueDiagnostic() {
      runTest("src/test/resources/testData/diagnostics/taskqueue/TaskQueueDiagnostic.kt");
    }
  }
}
