

package com.surrealdev.temporal.compiler.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.surrealdev.temporal.compiler.test.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/test/resources/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class TemporalBoxTestGenerated extends AbstractTemporalBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/resources/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("HandleWrapperClassLoads.kt")
  public void testHandleWrapperClassLoads() {
    runTest("src/test/resources/testData/box/HandleWrapperClassLoads.kt");
  }

  @Test
  @TestMetadata("InlineActivityCapturesAsArgs.kt")
  public void testInlineActivityCapturesAsArgs() {
    runTest("src/test/resources/testData/box/InlineActivityCapturesAsArgs.kt");
  }

  @Test
  @TestMetadata("InlineActivityClassLoads.kt")
  public void testInlineActivityClassLoads() {
    runTest("src/test/resources/testData/box/InlineActivityClassLoads.kt");
  }
}
